[package]
name = "ameda"
version = "0.1.1"
authors = ["aj <zencodes@ajjai.in>"]
description = "Manipulate 2D grid indices"
license = "GPL-3.0"
repository = "https://github.com/ajjaic/ameda"

[dependencies]
